/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as ProtectedBillIndexRouteImport } from './routes/_protected/bill/index'
import { Route as ProtectedSettingsShopManageIndexRouteImport } from './routes/_protected/settings/shop-manage/index'
import { Route as ProtectedSettingsOtherIndexRouteImport } from './routes/_protected/settings/other/index'
import { Route as ProtectedSettingsShopManageAddShopRouteImport } from './routes/_protected/settings/shop-manage/add-shop'
import { Route as ProtectedSettingsShopManageShopIdIndexRouteImport } from './routes/_protected/settings/shop-manage/$shopId/index'
import { Route as ProtectedSettingsShopManageShopIdEditShopRouteImport } from './routes/_protected/settings/shop-manage/$shopId/edit-shop'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const ProtectedBillIndexRoute = ProtectedBillIndexRouteImport.update({
  id: '/bill/',
  path: '/bill/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedSettingsShopManageIndexRoute =
  ProtectedSettingsShopManageIndexRouteImport.update({
    id: '/settings/shop-manage/',
    path: '/settings/shop-manage/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedSettingsOtherIndexRoute =
  ProtectedSettingsOtherIndexRouteImport.update({
    id: '/settings/other/',
    path: '/settings/other/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedSettingsShopManageAddShopRoute =
  ProtectedSettingsShopManageAddShopRouteImport.update({
    id: '/settings/shop-manage/add-shop',
    path: '/settings/shop-manage/add-shop',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedSettingsShopManageShopIdIndexRoute =
  ProtectedSettingsShopManageShopIdIndexRouteImport.update({
    id: '/settings/shop-manage/$shopId/',
    path: '/settings/shop-manage/$shopId/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedSettingsShopManageShopIdEditShopRoute =
  ProtectedSettingsShopManageShopIdEditShopRouteImport.update({
    id: '/settings/shop-manage/$shopId/edit-shop',
    path: '/settings/shop-manage/$shopId/edit-shop',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/login': typeof AuthLoginRoute
  '/bill/': typeof ProtectedBillIndexRoute
  '/settings/shop-manage/add-shop': typeof ProtectedSettingsShopManageAddShopRoute
  '/settings/other/': typeof ProtectedSettingsOtherIndexRoute
  '/settings/shop-manage/': typeof ProtectedSettingsShopManageIndexRoute
  '/settings/shop-manage/$shopId/edit-shop': typeof ProtectedSettingsShopManageShopIdEditShopRoute
  '/settings/shop-manage/$shopId/': typeof ProtectedSettingsShopManageShopIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ProtectedIndexRoute
  '/login': typeof AuthLoginRoute
  '/bill': typeof ProtectedBillIndexRoute
  '/settings/shop-manage/add-shop': typeof ProtectedSettingsShopManageAddShopRoute
  '/settings/other': typeof ProtectedSettingsOtherIndexRoute
  '/settings/shop-manage': typeof ProtectedSettingsShopManageIndexRoute
  '/settings/shop-manage/$shopId/edit-shop': typeof ProtectedSettingsShopManageShopIdEditShopRoute
  '/settings/shop-manage/$shopId': typeof ProtectedSettingsShopManageShopIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/bill/': typeof ProtectedBillIndexRoute
  '/_protected/settings/shop-manage/add-shop': typeof ProtectedSettingsShopManageAddShopRoute
  '/_protected/settings/other/': typeof ProtectedSettingsOtherIndexRoute
  '/_protected/settings/shop-manage/': typeof ProtectedSettingsShopManageIndexRoute
  '/_protected/settings/shop-manage/$shopId/edit-shop': typeof ProtectedSettingsShopManageShopIdEditShopRoute
  '/_protected/settings/shop-manage/$shopId/': typeof ProtectedSettingsShopManageShopIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/bill/'
    | '/settings/shop-manage/add-shop'
    | '/settings/other/'
    | '/settings/shop-manage/'
    | '/settings/shop-manage/$shopId/edit-shop'
    | '/settings/shop-manage/$shopId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/bill'
    | '/settings/shop-manage/add-shop'
    | '/settings/other'
    | '/settings/shop-manage'
    | '/settings/shop-manage/$shopId/edit-shop'
    | '/settings/shop-manage/$shopId'
  id:
    | '__root__'
    | '/_protected'
    | '/_auth'
    | '/_auth/login'
    | '/_protected/'
    | '/_protected/bill/'
    | '/_protected/settings/shop-manage/add-shop'
    | '/_protected/settings/other/'
    | '/_protected/settings/shop-manage/'
    | '/_protected/settings/shop-manage/$shopId/edit-shop'
    | '/_protected/settings/shop-manage/$shopId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_protected/bill/': {
      id: '/_protected/bill/'
      path: '/bill'
      fullPath: '/bill/'
      preLoaderRoute: typeof ProtectedBillIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/settings/shop-manage/': {
      id: '/_protected/settings/shop-manage/'
      path: '/settings/shop-manage'
      fullPath: '/settings/shop-manage/'
      preLoaderRoute: typeof ProtectedSettingsShopManageIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/settings/other/': {
      id: '/_protected/settings/other/'
      path: '/settings/other'
      fullPath: '/settings/other/'
      preLoaderRoute: typeof ProtectedSettingsOtherIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/settings/shop-manage/add-shop': {
      id: '/_protected/settings/shop-manage/add-shop'
      path: '/settings/shop-manage/add-shop'
      fullPath: '/settings/shop-manage/add-shop'
      preLoaderRoute: typeof ProtectedSettingsShopManageAddShopRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/settings/shop-manage/$shopId/': {
      id: '/_protected/settings/shop-manage/$shopId/'
      path: '/settings/shop-manage/$shopId'
      fullPath: '/settings/shop-manage/$shopId/'
      preLoaderRoute: typeof ProtectedSettingsShopManageShopIdIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/settings/shop-manage/$shopId/edit-shop': {
      id: '/_protected/settings/shop-manage/$shopId/edit-shop'
      path: '/settings/shop-manage/$shopId/edit-shop'
      fullPath: '/settings/shop-manage/$shopId/edit-shop'
      preLoaderRoute: typeof ProtectedSettingsShopManageShopIdEditShopRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedBillIndexRoute: typeof ProtectedBillIndexRoute
  ProtectedSettingsShopManageAddShopRoute: typeof ProtectedSettingsShopManageAddShopRoute
  ProtectedSettingsOtherIndexRoute: typeof ProtectedSettingsOtherIndexRoute
  ProtectedSettingsShopManageIndexRoute: typeof ProtectedSettingsShopManageIndexRoute
  ProtectedSettingsShopManageShopIdEditShopRoute: typeof ProtectedSettingsShopManageShopIdEditShopRoute
  ProtectedSettingsShopManageShopIdIndexRoute: typeof ProtectedSettingsShopManageShopIdIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedBillIndexRoute: ProtectedBillIndexRoute,
  ProtectedSettingsShopManageAddShopRoute:
    ProtectedSettingsShopManageAddShopRoute,
  ProtectedSettingsOtherIndexRoute: ProtectedSettingsOtherIndexRoute,
  ProtectedSettingsShopManageIndexRoute: ProtectedSettingsShopManageIndexRoute,
  ProtectedSettingsShopManageShopIdEditShopRoute:
    ProtectedSettingsShopManageShopIdEditShopRoute,
  ProtectedSettingsShopManageShopIdIndexRoute:
    ProtectedSettingsShopManageShopIdIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
