/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as ProtectedShopIndexRouteImport } from './routes/_protected/shop/index'
import { Route as ProtectedShopTableIndexRouteImport } from './routes/_protected/shop-table/index'
import { Route as ProtectedProductIndexRouteImport } from './routes/_protected/product/index'
import { Route as ProtectedFoodTypeIndexRouteImport } from './routes/_protected/food-type/index'
import { Route as ProtectedCartIndexRouteImport } from './routes/_protected/cart/index'
import { Route as ProtectedBillIndexRouteImport } from './routes/_protected/bill/index'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const ProtectedShopIndexRoute = ProtectedShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedShopTableIndexRoute = ProtectedShopTableIndexRouteImport.update({
  id: '/shop-table/',
  path: '/shop-table/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedProductIndexRoute = ProtectedProductIndexRouteImport.update({
  id: '/product/',
  path: '/product/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedFoodTypeIndexRoute = ProtectedFoodTypeIndexRouteImport.update({
  id: '/food-type/',
  path: '/food-type/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedCartIndexRoute = ProtectedCartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedBillIndexRoute = ProtectedBillIndexRouteImport.update({
  id: '/bill/',
  path: '/bill/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/bill/': typeof ProtectedBillIndexRoute
  '/cart/': typeof ProtectedCartIndexRoute
  '/food-type/': typeof ProtectedFoodTypeIndexRoute
  '/product/': typeof ProtectedProductIndexRoute
  '/shop-table/': typeof ProtectedShopTableIndexRoute
  '/shop/': typeof ProtectedShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/bill': typeof ProtectedBillIndexRoute
  '/cart': typeof ProtectedCartIndexRoute
  '/food-type': typeof ProtectedFoodTypeIndexRoute
  '/product': typeof ProtectedProductIndexRoute
  '/shop-table': typeof ProtectedShopTableIndexRoute
  '/shop': typeof ProtectedShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_protected/bill/': typeof ProtectedBillIndexRoute
  '/_protected/cart/': typeof ProtectedCartIndexRoute
  '/_protected/food-type/': typeof ProtectedFoodTypeIndexRoute
  '/_protected/product/': typeof ProtectedProductIndexRoute
  '/_protected/shop-table/': typeof ProtectedShopTableIndexRoute
  '/_protected/shop/': typeof ProtectedShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/bill/'
    | '/cart/'
    | '/food-type/'
    | '/product/'
    | '/shop-table/'
    | '/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/bill'
    | '/cart'
    | '/food-type'
    | '/product'
    | '/shop-table'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_auth'
    | '/_auth/login'
    | '/_protected/bill/'
    | '/_protected/cart/'
    | '/_protected/food-type/'
    | '/_protected/product/'
    | '/_protected/shop-table/'
    | '/_protected/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_protected/shop/': {
      id: '/_protected/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ProtectedShopIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/shop-table/': {
      id: '/_protected/shop-table/'
      path: '/shop-table'
      fullPath: '/shop-table/'
      preLoaderRoute: typeof ProtectedShopTableIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/product/': {
      id: '/_protected/product/'
      path: '/product'
      fullPath: '/product/'
      preLoaderRoute: typeof ProtectedProductIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/food-type/': {
      id: '/_protected/food-type/'
      path: '/food-type'
      fullPath: '/food-type/'
      preLoaderRoute: typeof ProtectedFoodTypeIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/cart/': {
      id: '/_protected/cart/'
      path: '/cart'
      fullPath: '/cart/'
      preLoaderRoute: typeof ProtectedCartIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/bill/': {
      id: '/_protected/bill/'
      path: '/bill'
      fullPath: '/bill/'
      preLoaderRoute: typeof ProtectedBillIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedBillIndexRoute: typeof ProtectedBillIndexRoute
  ProtectedCartIndexRoute: typeof ProtectedCartIndexRoute
  ProtectedFoodTypeIndexRoute: typeof ProtectedFoodTypeIndexRoute
  ProtectedProductIndexRoute: typeof ProtectedProductIndexRoute
  ProtectedShopTableIndexRoute: typeof ProtectedShopTableIndexRoute
  ProtectedShopIndexRoute: typeof ProtectedShopIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedBillIndexRoute: ProtectedBillIndexRoute,
  ProtectedCartIndexRoute: ProtectedCartIndexRoute,
  ProtectedFoodTypeIndexRoute: ProtectedFoodTypeIndexRoute,
  ProtectedProductIndexRoute: ProtectedProductIndexRoute,
  ProtectedShopTableIndexRoute: ProtectedShopTableIndexRoute,
  ProtectedShopIndexRoute: ProtectedShopIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
