/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as ProtectedSettingShopIndexRouteImport } from './routes/_protected/setting-shop/index'
import { Route as ProtectedBillIndexRouteImport } from './routes/_protected/bill/index'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const ProtectedSettingShopIndexRoute =
  ProtectedSettingShopIndexRouteImport.update({
    id: '/setting-shop/',
    path: '/setting-shop/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedBillIndexRoute = ProtectedBillIndexRouteImport.update({
  id: '/bill/',
  path: '/bill/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/login': typeof AuthLoginRoute
  '/bill/': typeof ProtectedBillIndexRoute
  '/setting-shop/': typeof ProtectedSettingShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ProtectedIndexRoute
  '/login': typeof AuthLoginRoute
  '/bill': typeof ProtectedBillIndexRoute
  '/setting-shop': typeof ProtectedSettingShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/bill/': typeof ProtectedBillIndexRoute
  '/_protected/setting-shop/': typeof ProtectedSettingShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/bill/' | '/setting-shop/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/bill' | '/setting-shop'
  id:
    | '__root__'
    | '/_protected'
    | '/_auth'
    | '/_auth/login'
    | '/_protected/'
    | '/_protected/bill/'
    | '/_protected/setting-shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_protected/setting-shop/': {
      id: '/_protected/setting-shop/'
      path: '/setting-shop'
      fullPath: '/setting-shop/'
      preLoaderRoute: typeof ProtectedSettingShopIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/bill/': {
      id: '/_protected/bill/'
      path: '/bill'
      fullPath: '/bill/'
      preLoaderRoute: typeof ProtectedBillIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedBillIndexRoute: typeof ProtectedBillIndexRoute
  ProtectedSettingShopIndexRoute: typeof ProtectedSettingShopIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedBillIndexRoute: ProtectedBillIndexRoute,
  ProtectedSettingShopIndexRoute: ProtectedSettingShopIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
